sudo: false

language: php

php:
    - 7.4
    - 7.3
    - 7.2
    - 7.1
    - 7.0

env:
  global:
    - DEFAULT=1

matrix:
  include:
    - php: 7.0
      env: PREFER_LOWEST=1

install:
    - composer install
    - if [[ $PREFER_LOWEST == 1 ]]; then composer update --prefer-lowest --prefer-dist --prefer-stable --no-interaction; fi
    - composer global require behat/behat phpspec/phpspec
    - export PATH=$PATH:$HOME/.config/composer/vendor/bin/

script:
    - phpspec run --verbose
    - behat
